services:
  web:
    container_name: web
    image: andrejch/testtask-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
      poetry run python manage.py migrate &&
      poetry run python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
        - "3000:3000"
    volumes:
        - .:/app:rw
    env_file:
        - .env
    depends_on:
      - web
    command: npm run start

volumes:
  postgres_data: